### ISSUE TITLE
CH375-Arduino

### ISSUE THREAD

**Issue by vvadimv** [gianluca-nitti/CH375-Arduino#3]
Hello!
When compiling with the Arduino Uno board, I get the following errors.

In file included from C:\Users\vvv\Documents\Arduino\libraries\CH375-Arduino-master\examples\USBPrinter\USBPrinter.ino:2:0:

C:\Users\vvv\Documents\Arduino\libraries\CH375-Arduino-master\src/CH375.h:3:22: fatal error: functional: No such file or directory

compilation terminated.

exit status 1
Error compiling for board Arduino/Genuino Uno.

How can I fix errors?

**Comment by gianluca-nitti** [comment]
Thanks for reporting, looks like that for some reason the toolchain for AVR boards does not include the [<functional> header from the C++ stdlib](http://www.cplusplus.com/reference/functional/), which was instead available in the arduino-ESP8266 toolchain for which this library was originally developed.
I worked around the issue by using an equivalent "C-style" function pointer in place of the `std::function` type I was using, and I now managed to compile the example for `Arduino/Genuino UNO`.

If you update the library from the current `master` branch of the repo it should work for you as well.
