### ISSUE TITLE
Connecting a Usb Mouse

### ISSUE THREAD

**Issue by Friday8229** [gianluca-nitti/CH375-Arduino#4]
Hi, i want to use a usb mouse with this chip(CH375), i am new to arduino, can you help me out with your library integration. I saw [http://www.electronicsfaq.com/2016/11/interface-usb-mouse-to-your-arduino.html?m=1](url) article but it is not working for me, the serial output is 37.

**Comment by gianluca-nitti** [comment]
This library, at the current state, does not have an high level mouse API. It can probably be ported from the [repository](https://github.com/xeecos/Me-USB-Host) mentioned in the article you linked.

**Comment by Friday8229** [comment]
Thanks for the reply. I bought a new module and everything works fine now.
